version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/dependabot"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions weekly
      interval: "weekly"
